name: "Fix PHP Code Styling"

on:
  push:
    branches: [main, 5.x]
    paths:
      - '**.php'
      - '.php-cs-fixer.php'
      - '.github/workflows/fix-php-code-styling.yml'
      - 'pint.json'
      - 'composer.json'
      - 'composer.lock'
  pull_request:
    branches: [main, 5.x]
    paths:
      - '**.php'
      - '.php-cs-fixer.php'
      - '.github/workflows/fix-php-code-styling.yml'
      - 'pint.json'
      - 'composer.json'
      - 'composer.lock'

permissions:
  contents: read

jobs:
  php-code-styling:
    name: PHP code style
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          coverage: none

      - name: Install composer dependencies
        uses: ramsey/composer-install@v3

      - name: Check code style
        run: composer lint
